M48
; DRILL file {KiCad (6.0.4)} date Fri Jun 17 20:48:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-17T20:48:31+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0157
%
G90
G05
T1
X8.9954Y-1.6552
X9.0564Y-1.7568
X9.0855Y-1.6486
T2
X8.9312Y-1.8619
X9.0552Y-1.8454
T0
M30
