
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: HCOC
*
* preset name: Color R5G6B5
* data block size: 16 bit(s), uint16_t
* RLE compression enabled: no
* conversion type: Color, not_used not_used
* split to rows: yes
* bits per pixel: 16
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint16_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include "HCOC.h"
#include <pgmspace.h>

// 图像数据数组
static const uint16_t image_data_HCOC_ppm_temp[20480] = {
    
};

const tImage HCOC = {
    image_data_HCOC_ppm_temp,
    160,  // 宽度
    128   // 高度
};

